# Netlify configuration for CTRL+ALT+BLOCK Therapy Platform
[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "22"
NODE_ENV = "production"
NPM_FLAGS = "--legacy-peer-deps"

# Next.js specific configuration
[[plugins]]
package = "@netlify/plugin-nextjs"

[functions]
node_bundler = "nft"
external_node_modules = ["postgres"]
included_files = ["lib/**"]
