# Netlify configuration for CTRL+ALT+BLOCK Therapy Platform
[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "22.18.0"
NODE_ENV = "production"

[[plugins]]
package = "@netlify/plugin-nextjs"
