# Minimal Netlify configuration
[build]
command = "npm run build"
publish = ".next"

[build.environment]
NODE_VERSION = "22"
NODE_ENV = "production"

# Essential Next.js plugin
[[plugins]]
package = "@netlify/plugin-nextjs"
