"use client";

import Image from "next/image";
import { ArrowRight, Bot, Award, ShieldQuestion } from "lucide-react";
import { PublicHeader } from "@/components/layout/public-header";
import { Button } from "@/components/ui/button";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export default function HomePage() {
  return (
    <div className="bg-background text-foreground flex min-h-screen flex-col">
      {/* top nav */}
      <PublicHeader />

      <main className="flex-1">
        {/* ───────────────────────────────── Hero */}
        <section className="relative overflow-hidden py-24">
          {/* hazy brand gradient */}
          <div className="pointer-events-none absolute inset-0 -z-10 bg-gradient-to-br from-pink-500/10 via-purple-500/10 to-indigo-500/10 blur-3xl" />

          <div className="mx-auto max-w-7xl flex flex-col-reverse lg:flex-row items-center lg:items-stretch gap-12 px-4 sm:px-6 lg:gap-20 lg:px-8 min-h-[400px]">
            {/* copy + CTA */}
            <div className="flex w-full flex-col justify-center items-center text-center lg:w-1/2 lg:items-start lg:text-left">
              <h1 className="mb-4 text-5xl font-extrabold leading-tight tracking-tight sm:text-6xl">
                Terminate. Format.
                <span className="block text-primary">Glow-up.</span>
              </h1>

              <p className="mt-4 max-w-xl text-lg text-muted-foreground">
                CTRL+ALT+BLOCK is the savage, AI-powered breakup ritual for
                deleting old attachments and rebooting your life. It’s not
                therapy – it’s a digital exorcism.
              </p>

              <div className="mt-8">
                <a href="/sign-up">
                  <Button
                    size="lg"
                    className="rounded-full bg-primary px-8 py-4 text-lg shadow-lg transition hover:bg-primary/80"
                  >
                    Begin the Ritual <ArrowRight className="ml-2 h-5 w-5" />
                  </Button>
                </a>
              </div>
            </div>

            {/* flagship artwork 400×400 */}
            <div className="flex w-full min-h-[400px] items-center justify-center lg:items-start lg:justify-end lg:w-1/2">
              <Image
                src="/hero-illustration.png"
                alt="Glitch-core emotional recovery illustration"
                width={400}
                height={400}
                className="drop-shadow-2xl transition-transform duration-500 hover:scale-105 rounded-2xl object-cover"
                priority
              />
            </div>
          </div>
        </section>

        {/* ───────────────────────────────── Feature grid */}
        <section className="bg-card/80 border-y border-border py-24">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="mb-16 text-center">
              <h2 className="text-4xl font-bold">
                Your Arsenal for Emotional Recovery
              </h2>
              <p className="mt-4 text-lg text-muted-foreground">
                Tools engineered for structured-chaos healing.
              </p>
            </div>

            <div className="grid grid-cols-1 gap-8 md:grid-cols-3">
              {[
                {
                  title: "AI-Powered Tools",
                  desc: "Closure chats, savage breakup letters, tarot-style diagnostics – all generated by our resident cyber-witch.",
                  icon: <Bot className="h-7 w-7" />,
                  bg: "bg-primary text-primary-foreground",
                  ring: "ring-primary/60",
                },
                {
                  title: "Gamified Healing",
                  desc: "Rack up No-Contact streaks, earn glitch badges and daily ritual XP. Reformatting emotions has never felt so good.",
                  icon: <Award className="h-7 w-7" />,
                  bg: "bg-accent text-accent-foreground",
                  ring: "ring-accent/60",
                },
                {
                  title: "Anonymous Confessional",
                  desc: "Scream into the void or lurk in the shadows. A privacy-first wall for chaotic catharsis.",
                  icon: <ShieldQuestion className="h-7 w-7" />,
                  bg: "bg-secondary text-secondary-foreground",
                  ring: "ring-secondary/60",
                },
              ].map(({ title, desc, icon, bg, ring }, i) => (
                <div
                  key={i}
                  className={`group rounded-2xl border border-border bg-card p-8 shadow-lg transition-transform duration-300 hover:scale-105 hover:ring-2 hover:${ring}`}
                >
                  <div
                    className={`mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full ${bg} shadow-inner`}
                  >
                    {icon}
                  </div>
                  <h3 className="mb-2 text-xl font-semibold">{title}</h3>
                  <p className="text-base text-muted-foreground">{desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ───────────────────────────────── Pricing / Free-trial */}
        <section className="py-24">
          <div className="mx-auto max-w-5xl px-4 text-center sm:px-6 lg:px-8">
            <h2 className="text-4xl font-bold">Pick your protocol</h2>
            <p className="mx-auto mt-4 max-w-2xl text-lg text-muted-foreground">
              Start free, stay petty. Upgrade when you want the full spellbook.
            </p>

            <div className="mt-16 grid gap-8 md:grid-cols-2">
              {/* freemium */}
              <div className="relative rounded-2xl border border-border bg-card p-8 shadow">
                <h3 className="text-2xl font-semibold">Freemium</h3>
                <p className="mt-2 text-sm text-muted-foreground">
                  Taste the chaos. No credit card.
                </p>
                <p className="mt-6 text-5xl font-extrabold">$0</p>
                <ul className="mt-6 space-y-2 text-left text-sm">
                  <li>✓ Limited AI rituals each day</li>
                  <li>✓ 7-day No-Contact streak counter</li>
                  <li>✓ Lurk-only Confessional access</li>
                </ul>
                <a href="/sign-up" className="mt-8 block">
                  <Button
                    size="lg"
                    className="w-full rounded-full bg-muted text-foreground hover:bg-muted/80"
                  >
                    Launch Free Mode
                  </Button>
                </a>
              </div>

              {/* basic w/ 7-day trial */}
              <div className="relative rounded-2xl border border-primary shadow-lg ring-2 ring-primary">
                <div className="absolute -top-3 right-6 rounded-full bg-primary px-3 py-1 text-xs font-semibold text-primary-foreground">
                  7-Day Free Trial
                </div>
                <div className="p-8">
                  <h3 className="text-2xl font-semibold">Basic</h3>
                  <p className="mt-2 text-sm text-muted-foreground">
                    Full ritual toolkit + daily AI.
                  </p>
                  <p className="mt-6 text-5xl font-extrabold">$9</p>
                  <p className="text-sm text-muted-foreground">per month</p>
                  <ul className="mt-6 space-y-2 text-left text-sm">
                    <li>✓ Unlimited Closure Simulator & generators</li>
                    <li>✓ Full Confessional access</li>
                    <li>✓ Streak badges & XP store</li>
                  </ul>
                  <a href="/sign-up" className="mt-8 block">
                    <Button
                      size="lg"
                      className="w-full rounded-full bg-primary text-primary-foreground hover:bg-primary/80"
                    >
                      Start Free Trial
                    </Button>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* ───────────────────────────────── FAQ */}
        <section className="border-t border-border bg-card/70 py-24">
          <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
            <h2 className="text-center text-4xl font-bold">FAQ</h2>
            <p className="mx-auto mt-4 max-w-2xl text-center text-lg text-muted-foreground">
              If you’re still emotionally buffering …
            </p>

            <Accordion type="single" collapsible className="mt-12 space-y-4">
              {[
                {
                  q: "Is CTRL+ALT+BLOCK therapy?",
                  a: "Nope. We’re a savage, creative ritual – perfect alongside therapy, but never a replacement.",
                },
                {
                  q: "Do I have to use my real name?",
                  a: "Absolutely not. We encourage anonymous usernames and store the bare minimum needed for log-in.",
                },
                {
                  q: "What happens if I break No-Contact?",
                  a: "Your streak resets (ouch) but you’ll unlock a ‘Recovery Ritual’ to process the slip without shame.",
                },
                {
                  q: "Can I cancel anytime?",
                  a: "Yes. Rage-quit, chill-quit, whatever-quit – one click in settings. Your exes do not get a notification :)",
                },
              ].map(({ q, a }, i) => (
                <AccordionItem key={i} value={`item-${i}`}>
                  <AccordionTrigger className="text-left text-lg font-medium">
                    {q}
                  </AccordionTrigger>
                  <AccordionContent className="text-muted-foreground">
                    {a}
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </section>

        {/* ───────────────────────────────── final CTA */}
        <section className="py-24">
          <div className="mx-auto max-w-3xl px-4 text-center sm:px-6 lg:px-8">
            <h2 className="text-4xl font-bold">Ready to block &amp; bless?</h2>
            <p className="mt-4 text-lg text-muted-foreground">
              Tap below, grab your 7-day trial, and start the emotional
              reboot today.
            </p>
            <div className="mt-8">
              <a href="/sign-up">
                <Button
                  size="lg"
                  className="rounded-full bg-primary px-8 py-4 text-lg shadow-xl transition hover:bg-primary/80"
                >
                  Enter CTRL+ALT+BLOCK <ArrowRight className="ml-3 h-6 w-6" />
                </Button>
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}